config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    resources :votes
  end

  root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: { minimum: 5 , message: 'Too short'}, uniqueness: true
  validates :content, presence: true
 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :vote

end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :post
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
   #to do this action only for owners of posts
  before_action :fetch_user_post, only: [:edit, :update, :destroy]
   #to sign in before these actions
  before_action :authenticate_user!, only: [:new, :update]
  def new
    @post = Post.new
  end

  def fetch_user_post
    # @post = Post.find_by(id: params[:id], user: current_user)
    @post = current_user.posts.find(params[:id])
  end

  def create
    @post = Post.create params[:post].permit(:title, :content)
    @post.user = current_user
    #@post.votes.up.by_type(current_user)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end
  
  def show
    @post = Post.find params[:id]

  end

  def edit 
    @post = Post.find params[:id]
  end

  def update
    @post = Post.find params[:id]
    if @post.update params[:post].permit(:title, :content)
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  def index
    @posts = Post.all
    @posts = @posts.sort_by{|post|
      Vote.where('upvote = 1 AND post_id = ?', post.id ).count - Vote.where('downvote = 1 AND post_id = ?', post.id ).count
    }.reverse!
    render 'index'
  end

  def destroy 
    @post = Post.find params[:id]
    @post.destroy
    redirect_to posts_path
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
#  before_action :chech_user_voted, only: [:new]
 #to sign in before these actions
  before_action :authenticate_user!, only: [:new]

  def new
    @post = Post.find params[:post_id]
    @vote = Vote.new
    @vote.upvote = params[:upvote].nil? ? 0 : 1
    @vote.downvote = params[:downvote].nil? ? 0 : 1
    @vote.post_id = @post.id
    @vote.user = current_user

    if @vote.save
            render status: 200, json: "OK"
    else
             render status: 500, json: "ERROR"
    end

  end

 # private

 #  def chech_user_voted
 #    return false
 #    # @post = Post.find_by(id: params[:id], user: current_user)
 #    @vote = current_user.vote.where('post_id = ? AND (upvote = 0 AND downvote = 1) AND (upvote = 1 AND downvote = 0 ) ',params[:post_id])
 #    if @vote.empty?
 #       # raise @vote.inspect
 #       false
 #    else
 #        flash[:notice]="You already voted!"
 #        @vote = []
 #        false
 #    end
 #  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def up_rating(post)
    Vote.where('post_id = ? AND upvote = 1', post.id).count
      
   # return 'Unrated' if vote ==

   # empty = 5 - rating
   # ('★' * rating) + ('☆' * empty)
  end
   def down_rating(post)
    Vote.where('post_id = ? AND downvote = 1', post.id).count
      
   # return 'Unrated' if vote ==

   # empty = 5 - rating
   # ('★' * rating) + ('☆' * empty)
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Reddit" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

   <ul class="nav nav-tabs">
    <li class="active"><a href="/">Reddit</a></li>
    <% if user_signed_in? %>
        <li>
         <%= link_to('Posts', posts_path)  %>
         </li>
         <li>
         <li><%= link_to t('.new', :default => t("helpers.links.new")),new_post_path %></li>
         </li>
         <li>
          <%= link_to('Edit profile', edit_user_registration_path) %>
          </li>
          <li>
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
          </li>
      <% else %>
         <li>
         <%= link_to('Login', new_user_session_path)  %>  
          </li>
          <li>
          <%= link_to('Register', new_user_registration_path)  %>
          </li>
         
      <% end %>
  </ul>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
           <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/posts/_form.html.erb
<% @post.errors.each do |attr,msg|  %>
 <%=msg%><br/>
<% end %>

<%= form_for @post, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :title, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :content, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :content, :class => 'text_field' %>
    </div>
  </div>

  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            posts_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/posts/edit.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/index.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:content) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
   
   
  <% if @posts.none? %>
    <tr>
      <td colspan='5'>
        No Posts yet!
      </td>
  </tr>
    <% else %>
     <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.id, post_path(post) %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= post.created_at %></td>
        <td>
          <a class="up-vote" data-vote="<%= new_post_vote_path(post)%>?upvote=1" href="<%= new_post_vote_path(post)%>?upvote=1">up<span><%= up_rating post %></span></a>
          
          <a class="down-vote" data-vote="<%= new_post_vote_path(post)%>?downvote=1" href="<%= new_post_vote_path(post)%>?downvote=1">down<span><%= down_rating post %></span></a>
           
            <% if post.user == current_user %>
              <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_post_path(post), :class => 'btn btn-default btn-xs' %>
              <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      post_path(post),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
            <% end %>
          
       
        </td>
         
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/posts/new.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/posts/show.html.erb
<%- model_class = Post -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @post.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:content) %>:</strong></dt>
  <dd><%= @post.content %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              posts_path, :class => 'btn btn-default'  %>
<% if @post.user == current_user %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
          edit_post_path(@post), :class => 'btn btn-default btn-xs' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
          post_path(@post),
          :method => :delete,
          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-xs btn-danger' %>
<% end %>

app/views/posts1/_form.html.erb
<%= form_for @posts, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
 
 
  <div class="control-group">
    <%= f.label :image_url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :image_url, :class => 'text_field' %>
    </div>
  </div>
  
<hr>
  
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            restaurants_path, :class => 'btn btn-default' %>
 
<% end %>

app/views/posts1/index.html.erb
<% if @posts.none? %>
No Posts yet!
<% end %>
<% @posts.each do |post| %>
<%= post.title %>
<%= truncate post.content, length: 140 %>

<% end %>

app/views/posts1/new.html.erb
<%= form_for @post do |f| %>
  <p>
    <b>Title</b><br />
    <%= f.text_field :title %>
  </p>
  <b>Content</b><br />
    <%= f.text_field :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/votes/index.html.erb
thank you for vote